# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GWP100_CH4": "00_core.ipynb",
         "get_emission_data_paths": "00_core.ipynb",
         "calc_temp_increase": "00_core.ipynb",
         "calc_gwpstar_emissions": "00_core.ipynb",
         "read_data": "00_core.ipynb",
         "make_gwps": "00_core.ipynb",
         "make_gwps_improved": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hydrocomputing.github.io/igwp/"

git_url = "https://github.com/hydrocomputing/igwp/tree/master/"

def custom_doc_links(name): return None
